
let resultado;

resultado = Math.PI;
resultado = Math.round(2.7) // redondea el dato dependiendo que total esta mas cerca <5 == 3  ###### >5== 2
resultado = Math.ceil(2.1)//siempre redondea hacia arriba
resultado = Math.floor(2.1)//siempre redondea hacia abajo
resultado = Math.sqrt(144)//raiz cuadrada
resultado = Math.abs(-2.7) //cambia los valores a positivo y si ya estan se queda en positivo
resultado = Math.min(1,5,6,6,7,25,94,10) //retorna el numero mas bajo
resultado = Math.max(1,5,6,6,7,25,94,10)//retorna el numero mas alto
resultado = Math.random() //da un numero aleatorio menor a 1 ejempolo 0.984165
resultado = Math.floor(Math.random() * 500)//da un numero aleatorio de 1 a 500



console.log(resultado)